server.port=9999
# THYMELEAF
# Whether to enable Thymeleaf view resolution for Web frameworks.
spring.thymeleaf.enabled=true
# Template files encoding.
spring.thymeleaf.encoding=UTF-8
# Whether to enable template caching.
spring.thymeleaf.cache=false
# Template mode to be applied to templates. See also Thymeleaf's TemplateMode enum.
spring.thymeleaf.mode=HTML
# Suffix that gets appended to view names when building a URL.
spring.thymeleaf.suffix=.html
# Prefix that gets prepended to view names when building a URL.
spring.thymeleaf.prefix=classpath:/templates/